### ISSUE TITLE
@Drawing doesn't work with non-English labels

### ISSUE THREAD

**Issue by NikolasTzimoulis** [League-of-Foundry-Developers/fvtt-module-trigger-happy#29]
This works:

`@Drawing[precipiceopen] @Trigger[click]  @Scene[uC8Dx07uojgY6lPx]{Απόκρημνος Τομέας}`

This doesn't work: 

`@Drawing[Απόκρημνος Τομέας] @Trigger[click]  @Scene[uC8Dx07uojgY6lPx]{Απόκρημνος Τομέας}`

**Comment by tposney** [comment]
This is a specific problem due to the tiny mce editor/html strings.
If I paste the string  
    Απόκρημνος Τομέας
I get  
\&Alpha;\&pi;ό\&kappa;\&rho;\&eta;\&mu;\&nu;\&omicron;\&sigmaf; \&Tau;\&omicron;\&mu;έ\&alpha;\&sigmaf;  
as the string to match against which of course fails.

I will need to give this some thrught, but if you know a good way to preprocess the text so that it becomnes a UTF string I can compared against it would be much easier.

**Comment by p4535992** [comment]
On my [PR #58](https://github.com/League-of-Foundry-Developers/fvtt-module-trigger-happy/pull/58), i bypassed this issue by using directly the id like this:
`@Drawing[uD8asx05uojgY6lPx] @Trigger[click] @Scene[uC8Dx07uojgY6lPx]` 
is not the perfect solution, but i think is acceptable

**Comment by p4535992** [comment]
On my [PR #58](https://github.com/League-of-Foundry-Developers/fvtt-module-trigger-happy/pull/58), you can do this:

`@Drawing[*] @Tag[my_english_label_reference]@Trigger[click] @Scene[uC8Dx07uojgY6lPx]{Απόκρημνος Τομέας}`

For each drawing element (with any Russian or Japanese label) in the current scene, filter by all those that have the 'my_english_label_reference' tag, in this case you decide by setting the tags if for one or more drawing elements. In this way your players will see the writing in the native language, while trigger happy use the English name set in the element '@Tag' for retrieve and start the trigger
