### ISSUE TITLE
Token Size reset at default 1x1 size

### ISSUE THREAD

**Issue by alexremy** [League-of-Foundry-Developers/fvtt-module-trigger-happy#42]
Hello, 

Recently upgraded to 0.8.8 (hosting on Forge) and most if not all tokens used for Trigger Happy do default to standard size (1x1) after a refresh page (F5 for instance), while they were set differently (3x0.5).
Also I noticed that when changing size in Prototype Tokens, no change is saved after updating token.

Any fix or workaround I can use?

Thanks!

**Comment by tposney** [comment]
Not sure. The display of the token is not something that trigger happy controls or influences as far as I know. I think it is a foundry thing, rather than a trigger happy thing. I know there have been some changes in the way tokens are managed in 0.8.8, but not really any idea of the details.

Changing the prototype token won't affect any tokens already on the map, you need to change the actual token on the map.  

I tried updating the prototype token, updating token, then dragging the actor to the canvas and the size change was reflected on the dropped token.  

Similarly, updating the on canvas token changed the size of the token.

Sorry, can't be more help.

**Comment by alexremy** [comment]
Thanks a lot for reaching out this quick. I solved my issue and indeed does look like it was Trigger Happy. For reference, I de-activated all modules and was able to change the token size, then re-activated them. 
Thanks a lot btw for your awesome module, I am a big fan/user!
I will close the issue
