### ISSUE TITLE
unknown tag

### ISSUE THREAD

**Issue by AjuP21** [League-of-Foundry-Developers/fvtt-module-trigger-happy#51]
Hi, I don't know whether something went wrong during the installation or what other problem is, At least most of the tags don't work for me at all. They don't even work in the examples. There is always only the message: Unknown Tag "Trigger" / Unknown Tag "Token" etc...

actors, scene and journal seem to work.

![fail](https://user-images.githubusercontent.com/90579062/133004009-8fc458db-7a3c-4e4c-a874-7838cd513287.jpg)

Foundry Vtt - version: 0.8.9

**Comment by tposney** [comment]
Usually, this means there are hidden HTML tags in your trigger journal. Edit the journal and select all the text and press the capital italic I which should remove the formatting HTML tags.

If that does not work, please export your journal entry and send it to me.

**Comment by AjuP21** [comment]
> Usually, this means there are hidden HTML tags in your trigger journal. Usually this happens if you copy/paste from a formatted string, e.g. a web page. Edit the journal and select all the text and press the capital italic I which should remove the formatting HTML tags. If that does not work, please export your journal entry and send it to me.

I tried both copy / paste and manual writing of the command. Neither worked.
To start with, I just want to make invisible buttons for my landing page, but unfortunately it doesn't work without the click trigger.
![fail2](https://user-images.githubusercontent.com/90579062/133120009-55258825-1ba0-46a8-ba06-17ec6e7a5a58.jpg)
[fvtt-JournalEntry-triggers.zip](https://github.com/League-of-Foundry-Developers/fvtt-module-trigger-happy/files/7155820/fvtt-JournalEntry-triggers.zip)

**Comment by matbaren** [comment]
Hello! I'm having the same exact "issue" here - Foundry 0.8.9 and Trigger Happy 0.8.8

The actor, scene, item and macro tags appear linked, but **Trigger**, **ChatMessage** and **Token**, at least, display the **"Unknown Tag"** message and the unlinked icon (There are no HTML tags hidden).

**Nevertheles, the triggers ARE working..** 
(I can't get the **Token** tag to work though, but at least for the things I wanted to do, it worked using "Actor" instead)

@AjuP21 First make sure that the Trigger Happy icon IS enabled in the left toolbar. (Check @tposney reply in issue 41 if you don't know where the icon is). I got my landing page working last week when I found that response.. I've got no memory of ever disabling it, but it was off. At first I thought that I made it work by directly removing the "Trigger[click]" from each trigger sentence,  (if it doesn't work with enabling the Trigger Happy icon, try doing that) But just tested leaving the Trigger[click] written and it works in spite of being unlinked, and the Unknown Tag thing.. 

It's a great module guys!!. 
Thank you so much for your work!

**Comment by tposney** [comment]
I think there must be some other module handling the link display - since I get 

![Screenshot from 2021-09-14 15-19-19](https://user-images.githubusercontent.com/4486143/133200084-0eb50d5b-b9e6-463f-915f-724cb94b5d63.jpg)

The first 2 red links make sense since I don't have those actors in my world.
The 3rd line also makes sense since it is not a "standard" link and the 4th line I added to make sure that things were working.

To rule out any import/export curing of the problem  an you import the triggers journal and see what happens?
Lastly can you check if there are any link processing modules you have installed? Or try in a world with no other modules other than trigger happy.

**Comment by tposney** [comment]
> (I can't get the **Token** tag to work though, but at least for the things I wanted to do, it worked using "Actor" instead)

The @Token[TokeName] uses the name from the token settings, and must be an exact match including upper/lower case.

![pic](https://user-images.githubusercontent.com/4486143/133201532-dda05b47-d3bb-4423-97db-7a8c0fab0488.PNG)

> @AjuP21 First make sure that the Trigger Happy icon IS enabled in the left toolbar. 

There is a module config setting to disable that button completely if you want.

The default behaviour for @Token and @Actor links is "click", so the @Trigger[click] is not really required for those. I tend to put them in so I know what is being done. The @click unknown tag is confusing to me since I don't get that in my world.

**Comment by AjuP21** [comment]
well...
it seems that the links actually work, even though I have the unknown tag there ...
My goal was to hide the tokens so that you can't see the frame and so that they still work, I need the click trigger.
So far it hadn't worked, but I probably tinkered with the settings for so long that I finally got it to work.
the unknown tag seems to be a display error ...
![failsolved](https://user-images.githubusercontent.com/90579062/133234412-07e602dd-c9d5-4512-98e9-da951922eb93.jpg)

it could actually be that the trigger happy icon in the toolbar was switched off first
so that it doesn't accidentally happen again, i have hidden it in the settings. 
Thanks for the hint!
